services:

  coti-full-node-genesis-1:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-1
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-1/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-1:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-1
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --port=7400
      - --identity=cotiagents-node-1
      - --verbosity=3
      - --datadir=/execution/node1
      - --syncmode=full
      - --ws
      - --ws.port=8446
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8545:8545"
      - "8446:8446"
      - "7400:7400"
    depends_on:
      coti-full-node-genesis-1:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-1:/execution/
      - ./execution/node-1/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coti-full-node-genesis-2:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-2
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-2/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-2:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-2
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8546
      - --port=7401
      - --identity=cotiagents-node-2
      - --verbosity=3
      - --datadir=/execution/node2
      - --syncmode=full
      - --ws
      - --ws.port=8447
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8546:8546"
      - "8447:8447"
      - "7401:7401"
    depends_on:
      coti-full-node-genesis-2:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-2:/execution/
      - ./execution/node-2/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coti-full-node-genesis-3:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-3
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-3/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-3:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-3
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8547
      - --port=7402
      - --identity=cotiagents-node-3
      - --verbosity=3
      - --datadir=/execution/node3
      - --syncmode=full
      - --ws
      - --ws.port=8448
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8547:8547"
      - "8448:8448"
      - "7402:7402"
    depends_on:
      coti-full-node-genesis-3:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-3:/execution/
      - ./execution/node-3/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coti-full-node-genesis-4:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-4
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-4/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-4:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-4
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8548
      - --port=7403
      - --identity=cotiagents-node-4
      - --verbosity=3
      - --datadir=/execution/node4
      - --syncmode=full
      - --ws
      - --ws.port=8449
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8548:8548"
      - "8449:8449"
      - "7403:7403"
    depends_on:
      coti-full-node-genesis-4:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-4:/execution/
      - ./execution/node-4/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coti-full-node-genesis-5:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-5
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-5/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-5:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-5
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8549
      - --port=7404
      - --identity=cotiagents-node-5
      - --verbosity=3
      - --datadir=/execution/node5
      - --syncmode=full
      - --ws
      - --ws.port=8450
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8549:8549"
      - "8450:8450"
      - "7404:7404"
    depends_on:
      coti-full-node-genesis-5:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-5:/execution/
      - ./execution/node-5/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coti-full-node-genesis-6:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-6
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-6/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-6:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-6
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8550
      - --port=7405
      - --identity=cotiagents-node-6
      - --verbosity=3
      - --datadir=/execution/node6
      - --syncmode=full
      - --ws
      - --ws.port=8451
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8550:8550"
      - "8451:8451"
      - "7405:7405"
    depends_on:
      coti-full-node-genesis-6:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-6:/execution/
      - ./execution/node-6/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coti-full-node-genesis-7:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-7
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-7/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-7:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-7
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8551
      - --port=7406
      - --identity=cotiagents-node-7
      - --verbosity=3
      - --datadir=/execution/node7
      - --syncmode=full
      - --ws
      - --ws.port=8452
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8551:8551"
      - "8452:8452"
      - "7406:7406"
    depends_on:
      coti-full-node-genesis-7:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-7:/execution/
      - ./execution/node-7/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coti-full-node-genesis-8:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-8
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-8/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-8:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-8
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8552
      - --port=7407
      - --identity=cotiagents-node-8
      - --verbosity=3
      - --datadir=/execution/node8
      - --syncmode=full
      - --ws
      - --ws.port=8453
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8552:8552"
      - "8453:8453"
      - "7407:7407"
    depends_on:
      coti-full-node-genesis-8:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-8:/execution/
      - ./execution/node-8/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coti-full-node-genesis-9:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-9
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-9/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-9:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-9
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8553
      - --port=7408
      - --identity=cotiagents-node-9
      - --verbosity=3
      - --datadir=/execution/node9
      - --syncmode=full
      - --ws
      - --ws.port=8454
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8553:8553"
      - "8454:8454"
      - "7408:7408"
    depends_on:
      coti-full-node-genesis-9:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-9:/execution/
      - ./execution/node-9/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coti-full-node-genesis-10:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-genesis-10
    command: --datadir=/execution init /coti-genesis/genesis.json
    volumes:
      - ./execution/node-10/:/execution
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  coti-full-node-10:
    image: coti/full-node:1.1.3
    container_name: coti-full-node-10
    command:
      - --soda.engine
      - --soda.seqaddr=0x7d9938777950631645B5B16057A2c52391a8e787
      - --soda.exec1addr=0x787A4bB8677189682AD2AFf2becB78A2ED9d1241
      - --soda.exec2addr=0x183B8933c370A2736c9766379349D72154Bd0b8f
      - --soda.validator
      - --networkid=7082400
      - --http
      - --http.api=eth,net,web3,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8554
      - --port=7409
      - --identity=cotiagents-node-10
      - --verbosity=3
      - --datadir=/execution/node10
      - --syncmode=full
      - --ws
      - --ws.port=8455
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=web3,eth
      - --metrics
      - --metrics.expensive
      - --metrics.addr=0.0.0.0
      - --rpc.allow-unprotected-txs=true
      - --miner.gasprice=5000000
      - --bootnodes=enode://8c14ae1db71cc9796bf04cf3cc5508291621bc8b9c4c80d4d7b79d8e4b33eadcfc2298242362443fd1317c5ac887dae8e8fe9c551d7792f2bc2e7177978f730a@147.135.77.48:7400,enode://820748e65666a7444199808ecbe80f4133fa9faa7618520eb6577466336daef7aa40910a2d03dd93766ccb7b93fecdfd1a9ff32e01217235fddc3c990928fa16@63.176.21.19:7400
      - --nat=extip:113.23.114.95
    ports:
      - "8554:8554"
      - "8455:8455"
      - "7409:7409"
    depends_on:
      coti-full-node-genesis-10:
        condition: service_completed_successfully
    volumes:
      - ./execution/node-10:/execution/
      - ./execution/node-10/keystore:/execution/keystore
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
